
import java.awt.Color;
import java.rmi.Naming;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shree pc
 */
public class feedback extends javax.swing.JFrame {

    /**
     * Creates new form feedback
     */
    String ip;
    public feedback(String ip) {
        initComponents();
        this.ip=ip;
     jLabel5.setOpaque(false);
      jLabel5.setBackground(new Color(0,0,0,128));
jLabel4.setOpaque(false);
      jLabel4.setBackground(new Color(0,0,0,128));
jLabel1.setOpaque(false);
      jLabel1.setBackground(new Color(0,0,0,128));
jLabel6.setOpaque(false);
      jLabel6.setBackground(new Color(0,0,0,128));
  msgsub.getViewport().setOpaque(false);
  body.getViewport().setOpaque(false);
body1.setOpaque(false);
     body1.setBackground(new Color(0,0,0,128));
msgsub1.setOpaque(false);
      msgsub1.setBackground(new Color(0,0,0,128));
usertext1.setOpaque(false);
      usertext1.setBackground(new Color(0,0,0,128));
usertext2.setOpaque(false);
      usertext2.setBackground(new Color(0,0,0,128));
usertext.setOpaque(false);
      usertext.setBackground(new Color(0,0,0,128));
      msgsub1.setCaretPosition(msgsub1.getText().length());
    msgsub1.getCaret().setVisible(true);
    
    msgsub1.setLineWrap(true);
    body1.setLineWrap(true);
    }
      public feedback() {
        initComponents();
     jLabel5.setOpaque(false);
      jLabel5.setBackground(new Color(0,0,0,128));
jLabel4.setOpaque(false);
      jLabel4.setBackground(new Color(0,0,0,128));
jLabel1.setOpaque(false);
      jLabel1.setBackground(new Color(0,0,0,128));
jLabel6.setOpaque(false);
      jLabel6.setBackground(new Color(0,0,0,128));
  msgsub.getViewport().setOpaque(false);
  body.getViewport().setOpaque(false);
body1.setOpaque(false);
     body1.setBackground(new Color(0,0,0,128));
msgsub1.setOpaque(false);
      msgsub1.setBackground(new Color(0,0,0,128));
usertext1.setOpaque(false);
      usertext1.setBackground(new Color(0,0,0,128));
usertext2.setOpaque(false);
      usertext2.setBackground(new Color(0,0,0,128));
usertext.setOpaque(false);
      usertext.setBackground(new Color(0,0,0,128));
  msgsub1.setCaretPosition(msgsub1.getText().length());
    msgsub1.getCaret().setVisible(true);
   
    msgsub1.setLineWrap(true);
    body1.setLineWrap(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        msgsub = new javax.swing.JScrollPane();
        msgsub1 = new javax.swing.JTextArea();
        body = new javax.swing.JScrollPane();
        body1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        usertext1 = new javax.swing.JTextField();
        watermark = new javax.swing.JLabel();
        usertext = new javax.swing.JTextField();
        usertext2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1368, 768));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 100)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FEEDBACK");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 3, true));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(410, 10, 520, 110);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Message Subject:");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 190, 220, 36);

        msgsub.setBorder(new javax.swing.border.MatteBorder(null));
        msgsub.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        msgsub.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        msgsub1.setColumns(20);
        msgsub1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        msgsub1.setForeground(new java.awt.Color(255, 255, 255));
        msgsub1.setLineWrap(true);
        msgsub1.setRows(5);
        msgsub1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        msgsub1.setCaretColor(new java.awt.Color(255, 255, 255));
        msgsub1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        msgsub1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        msgsub.setViewportView(msgsub1);

        jPanel1.add(msgsub);
        msgsub.setBounds(390, 190, 550, 70);

        body.setBorder(new javax.swing.border.MatteBorder(null));

        body1.setColumns(20);
        body1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        body1.setForeground(new java.awt.Color(255, 255, 255));
        body1.setLineWrap(true);
        body1.setRows(5);
        body1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        body.setViewportView(body1);

        jPanel1.add(body);
        body.setBounds(390, 330, 550, 240);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/arrow-back-icon.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setPreferredSize(new java.awt.Dimension(64, 64));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1320, 10, 50, 64);

        usertext1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usertext1.setForeground(new java.awt.Color(255, 255, 255));
        usertext1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        usertext1.setOpaque(false);
        usertext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertext1ActionPerformed(evt);
            }
        });
        jPanel1.add(usertext1);
        usertext1.setBounds(390, 680, 550, 40);

        watermark.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        watermark.setText("TEAM NEWNETIC™");
        jPanel1.add(watermark);
        watermark.setBounds(1190, 740, 173, 24);

        usertext.setEditable(false);
        usertext.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        usertext.setForeground(new java.awt.Color(255, 255, 255));
        usertext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usertext.setText("SUBMIT");
        usertext.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(0, 0, 0)));
        usertext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usertext.setOpaque(false);
        usertext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertextMouseClicked(evt);
            }
        });
        usertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertextActionPerformed(evt);
            }
        });
        jPanel1.add(usertext);
        usertext.setBounds(1080, 420, 140, 40);

        usertext2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usertext2.setForeground(new java.awt.Color(255, 255, 255));
        usertext2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        usertext2.setOpaque(false);
        usertext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertext2ActionPerformed(evt);
            }
        });
        jPanel1.add(usertext2);
        usertext2.setBounds(390, 610, 550, 40);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Reply Email:");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 680, 160, 36);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Reply Name: ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 610, 160, 36);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("BODY:");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 330, 90, 36);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/if_brightness_1055105.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 130, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/1920x1080-indigo-web-solid-color-background.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1380, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextActionPerformed

    private void usertext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertext1ActionPerformed

    private void usertext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertext2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertext2ActionPerformed

    private void usertextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertextMouseClicked
    try{
        serverinterface s1=(serverinterface)Naming.lookup("rmi://"+ip+"/tag");
        s1.insertFeedback(msgsub1.getText(),body1.getText(),usertext2.getText(),usertext1.getText());
        msgsub1.setText("");
        body1.setText("");
        usertext2.setText("");
        usertext1.setText("");
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    }//GEN-LAST:event_usertextMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        new Instruction1(ip).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane body;
    private javax.swing.JTextArea body1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane msgsub;
    private javax.swing.JTextArea msgsub1;
    private javax.swing.JTextField usertext;
    private javax.swing.JTextField usertext1;
    private javax.swing.JTextField usertext2;
    private javax.swing.JLabel watermark;
    // End of variables declaration//GEN-END:variables
}
