


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Timer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shree pc
 */
public class lanengine extends javax.swing.JFrame {
//
    /**
     * Creates new form lanengine1
     */
    public lanengine() 
    {
     initComponents();
    Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
    int sw=(int)(d.getWidth());
    int sh=(int)(d.getHeight());
     setLocation((sw-400)/2,(sh-270)/2);
    setBounds(0,0,sw,sh); 
    IPenter.setVisible(false);
    enter.setVisible(false);
    IP.setVisible(false);
    tick1.setVisible(false); 
    IPenter.setOpaque(false);
    IPenter.setBackground(new Color(0,0,0,128));
      jLabel6.setVisible(false);
          jLabel4.setVisible(false);
     
    t=new javax.swing.Timer(7000,new MyTimer());
        t.start();
         
    }
    javax.swing.Timer t;
    public class MyTimer implements ActionListener
    {
        public void actionPerformed(ActionEvent e)
        {
            t.stop();
            jLabel5.setVisible(false);
        jLabel3.setVisible(false);
        tick1.setVisible(true);
        
        IPenter.setVisible(true);
    enter.setVisible(true);
    IP.setVisible(true);
    
                 
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tick = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tick1 = new javax.swing.JLabel();
        IPenter = new javax.swing.JTextField();
        watermark = new javax.swing.JLabel();
        enter = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IP = new javax.swing.JLabel();
        mainpage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Books-300x300.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(540, 230, 300, 290);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText(" EXAM SOFTWARE");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 340, 430, 90);

        tick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/if_Close_Icon_Circle_1398920.png"))); // NOI18N
        tick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tickMouseClicked(evt);
            }
        });
        jPanel2.add(tick);
        tick.setBounds(1300, 20, 50, 50);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel5.setText("LOADING.....");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(570, 610, 140, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/copper-loader.gif"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(560, 580, 270, 70);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("WELCOME TO THE PORTAL");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(570, 540, 260, 30);

        tick1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/if_Tick_Mark_Circle_1398913.png"))); // NOI18N
        tick1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tick1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tick1MouseClicked(evt);
            }
        });
        jPanel2.add(tick1);
        tick1.setBounds(1140, 430, 50, 50);

        IPenter.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        IPenter.setForeground(new java.awt.Color(204, 204, 255));
        IPenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IPenterMouseClicked(evt);
            }
        });
        IPenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPenterActionPerformed(evt);
            }
        });
        jPanel2.add(IPenter);
        IPenter.setBounds(990, 380, 360, 40);

        watermark.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        watermark.setText("TEAM NEWNETIC™");
        jPanel2.add(watermark);
        watermark.setBounds(1170, 730, 180, 30);

        enter.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter.setForeground(new java.awt.Color(204, 204, 255));
        enter.setText("Enter the Server IP");
        jPanel2.add(enter);
        enter.setBounds(920, 300, 300, 60);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Please enter a valid IP");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(1000, 520, 210, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/if_3_330411(1).png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(930, 510, 70, 60);

        IP.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        IP.setForeground(new java.awt.Color(204, 204, 255));
        IP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IP.setText("IP");
        jPanel2.add(IP);
        IP.setBounds(910, 380, 60, 40);

        mainpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/1920x1080-indigo-web-solid-color-background.jpg"))); // NOI18N
        mainpage.setText("jLabel4");
        jPanel2.add(mainpage);
        mainpage.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IPenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPenterActionPerformed

    private void tickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tickMouseClicked
      dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_tickMouseClicked

    private void tick1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tick1MouseClicked
        
        String ip=IPenter.getText();
        Instruction1 obj=new Instruction1(ip);
        if(IPenter.getText().equals(""))
        {
          
            jLabel6.setVisible(true);
          jLabel4.setVisible(true);
        }
        else
        {
           obj.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_tick1MouseClicked

    private void IPenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IPenterMouseClicked
       jLabel6.setVisible(false);
          jLabel4.setVisible(false);
                 
    }//GEN-LAST:event_IPenterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lanengine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lanengine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lanengine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lanengine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lanengine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IP;
    private javax.swing.JTextField IPenter;
    private javax.swing.JLabel enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mainpage;
    private javax.swing.JLabel tick;
    private javax.swing.JLabel tick1;
    private javax.swing.JLabel watermark;
    // End of variables declaration//GEN-END:variables
}
