/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shree pc
 */
public class ServerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enter = new javax.swing.JLabel();
        enter1 = new javax.swing.JLabel();
        enter2 = new javax.swing.JLabel();
        enter3 = new javax.swing.JLabel();
        enter4 = new javax.swing.JLabel();
        enter5 = new javax.swing.JLabel();
        enter10 = new javax.swing.JLabel();
        enter6 = new javax.swing.JLabel();
        enter7 = new javax.swing.JLabel();
        enter8 = new javax.swing.JLabel();
        enter9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mainpage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1368, 768));
        jPanel1.setLayout(null);

        enter.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter.setForeground(new java.awt.Color(204, 204, 255));
        enter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter.setText("CSE");
        enter.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterMouseClicked(evt);
            }
        });
        jPanel1.add(enter);
        enter.setBounds(600, 70, 300, 60);

        enter1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter1.setForeground(new java.awt.Color(204, 204, 255));
        enter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter1.setText("ME");
        enter1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter1MouseClicked(evt);
            }
        });
        jPanel1.add(enter1);
        enter1.setBounds(600, 570, 300, 60);

        enter2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter2.setForeground(new java.awt.Color(204, 204, 255));
        enter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter2.setText("EN");
        enter2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter2MouseClicked(evt);
            }
        });
        jPanel1.add(enter2);
        enter2.setBounds(600, 260, 300, 60);

        enter3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter3.setForeground(new java.awt.Color(204, 204, 255));
        enter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter3.setText("IT");
        enter3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter3MouseClicked(evt);
            }
        });
        jPanel1.add(enter3);
        enter3.setBounds(600, 470, 300, 60);

        enter4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter4.setForeground(new java.awt.Color(204, 204, 255));
        enter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter4.setText("Feedback");
        enter4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter4MouseClicked(evt);
            }
        });
        jPanel1.add(enter4);
        enter4.setBounds(60, 570, 300, 60);

        enter5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter5.setForeground(new java.awt.Color(204, 204, 255));
        enter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter5.setText("ECE");
        enter5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter5MouseClicked(evt);
            }
        });
        jPanel1.add(enter5);
        enter5.setBounds(600, 370, 300, 60);

        enter10.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter10.setForeground(new java.awt.Color(204, 204, 255));
        enter10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter10.setText("Result Of Students");
        enter10.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter10MouseClicked(evt);
            }
        });
        jPanel1.add(enter10);
        enter10.setBounds(600, 660, 300, 60);

        enter6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter6.setForeground(new java.awt.Color(204, 204, 255));
        enter6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter6.setText("Practice");
        enter6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter6MouseClicked(evt);
            }
        });
        jPanel1.add(enter6);
        enter6.setBounds(60, 400, 300, 60);

        enter7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter7.setForeground(new java.awt.Color(204, 204, 255));
        enter7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter7.setText("Registered Students");
        enter7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter7MouseClicked(evt);
            }
        });
        jPanel1.add(enter7);
        enter7.setBounds(60, 70, 300, 60);

        enter8.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter8.setForeground(new java.awt.Color(204, 204, 255));
        enter8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter8.setText("Aptitude");
        enter8.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter8MouseClicked(evt);
            }
        });
        jPanel1.add(enter8);
        enter8.setBounds(60, 230, 300, 60);

        enter9.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 28)); // NOI18N
        enter9.setForeground(new java.awt.Color(204, 204, 255));
        enter9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter9.setText("CE");
        enter9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        enter9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enter9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter9MouseClicked(evt);
            }
        });
        jPanel1.add(enter9);
        enter9.setBounds(600, 170, 300, 60);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGOUT");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1220, 30, 130, 40);

        mainpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/1920x1080-indigo-web-solid-color-background.jpg"))); // NOI18N
        mainpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainpageMouseClicked(evt);
            }
        });
        jPanel1.add(mainpage);
        mainpage.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainpageMouseClicked
     
    }//GEN-LAST:event_mainpageMouseClicked

    private void enter7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter7MouseClicked
      new frame(enter7.getText()).setVisible(true);
      
    }//GEN-LAST:event_enter7MouseClicked

    private void enter8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter8MouseClicked
      new frame(enter8.getText()).setVisible(true);
    }//GEN-LAST:event_enter8MouseClicked

    private void enter6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter6MouseClicked
    new frame(enter6.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enter6MouseClicked

    private void enter4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter4MouseClicked
    new frame(enter4.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enter4MouseClicked

    private void enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseClicked
    new frame(enter.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enterMouseClicked

    private void enter9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter9MouseClicked
    new frame(enter9.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enter9MouseClicked

    private void enter2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter2MouseClicked
    new frame(enter2.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enter2MouseClicked

    private void enter5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter5MouseClicked
    new frame(enter5.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enter5MouseClicked

    private void enter3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter3MouseClicked
    new frame(enter3.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enter3MouseClicked

    private void enter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1MouseClicked
    new frame(enter1.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enter1MouseClicked

    private void enter10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter10MouseClicked
    new frame(enter10.getText()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_enter10MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
      this.setVisible(false);
      new LOGIN().setVisible(true);
      
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enter;
    private javax.swing.JLabel enter1;
    private javax.swing.JLabel enter10;
    private javax.swing.JLabel enter2;
    private javax.swing.JLabel enter3;
    private javax.swing.JLabel enter4;
    private javax.swing.JLabel enter5;
    private javax.swing.JLabel enter6;
    private javax.swing.JLabel enter7;
    private javax.swing.JLabel enter8;
    private javax.swing.JLabel enter9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainpage;
    // End of variables declaration//GEN-END:variables
}
